apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orcha.fullname" . }}
  labels:
    {{- include "orcha.labels" . | nindent 4 }}
data:
  AUTH_DISABLED: {{ .Values.config.authDisabled | quote }}
  TEMPORAL_HOST: {{ tpl .Values.config.temporalHost . | quote }}
  TEMPORAL_NAMESPACE: {{ .Values.config.temporalNamespace | quote }}
  PGUSER: {{ .Values.postgresqlExternal.username | quote }}
  PGHOST: {{ .Values.postgresqlExternal.hostname | quote }}
  PGPORT: {{ .Values.postgresqlExternal.port | quote }}
  PGDATABASE: {{ .Values.postgresqlExternal.database | quote }}

